### ISSUE TITLE
Error: Run Entire Set-Up and Set Up Chracter

### ISSUE THREAD

**Issue by honestcactus** [michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders#122]
Tested in Blender 3.4, 4.0, 4.1

Attempting to Set Up Character results in the same error message. Tested with 4 different characters from varying sources.

**3.4 & 4.0**
```
Python: Traceback (most recent call last):
  File "\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\setup_wizard\genshin_import_character_model.py", line 83, in execute
    self.import_character_model(character_model_file_path_or_directory, is_character_model_file)
  File "\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\setup_wizard\genshin_import_character_model.py", line 115, in import_character_model
    bpy.ops.better_import.fbx(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  BETTER_IMPORT_OT_fbx.filepath doesn't support None from string types
```

**4.1**
```
Python: Traceback (most recent call last):
  File "\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\setup_wizard\genshin_import_character_model.py", line 83, in execute
    self.import_character_model(character_model_file_path_or_directory, is_character_model_file)
  File "\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\setup_wizard\genshin_import_character_model.py", line 115, in import_character_model
    bpy.ops.better_import.fbx(
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties:  BETTER_IMPORT_OT_fbx.filepath doesn't support None from string types
```

**Comment by michael-gh1** [comment]
Hi @honestcactus, looks like the error you're getting is the same for each of the versions you tried.

While the addon doesn't support 3.4 and 4.1, I do think the issue you're specifically having is unrelated to the Blender version you're using.

This error suggests to me that the Setup Wizard is not finding an `.fbx` file in the folder you are selecting. Could you provide your setup (folder structure, where is the `.fbx` file and what you're selecting) and steps to reproduce your issue?

For example, I'm able to reproduce this error if I select a folder with no `.fbx` file in it. But if I select the exact `.fbx` file or the folder containing the `.fbx` file, I am able to successfully import the character model.

**Comment by honestcactus** [comment]
> Hi @honestcactus, looks like the error you're getting is the same for each of the versions you tried.
> 
> While the addon doesn't support 3.4 and 4.1, I do think the issue you're specifically having is unrelated to the Blender version you're using.
> 
> This error suggests to me that the Setup Wizard is not finding an `.fbx` file in the folder you are selecting. Could you provide your setup (folder structure, where is the `.fbx` file and what you're selecting) and steps to reproduce your issue?
> 
> For example, I'm able to reproduce this error if I select a folder with no `.fbx` file in it. But if I select the exact `.fbx` file or the folder containing the `.fbx` file, I am able to successfully import the character model.

Ah that seems to be the issue, the official models are offered as `.pmx` not `.fbx` files. Here's is one folder in question.
![image](https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/assets/19522057/8bcfab9e-2edf-4bf0-ba95-1eaa3da8f9fa)

I did also attempt to import the `.pmx` model via a MMD addon but that doesn't seem to work either.

**Comment by michael-gh1** [comment]
Sorry for the late replies, this fell off my plate

@honestcactus there may be some .fbx files floating around that should work with the setup wizard. I haven't tried importing .pmx models and I'm not sure if the shader supports them either.

@zhangjiading152 there's a few guides in Omatsuri that point to youtube videos, let me try to get those links updated/removed soon. I was previously hosting them on Discord (terrible idea) from 2+ years ago and they had a recent-ish change that wiped them.

**Comment by zyzydo** [comment]
Hello, I had a problem trying to import a Model for honkai star rail. 
![image](https://github.com/user-attachments/assets/5591c01c-0f8f-4d91-8938-b85d1a5597c8)

**Comment by michael-gh1** [comment]
@zyzydo, looks like it is failing when trying to import the character model using the addon BetterFBX.

It may be that you're using an older version of BetterFBX or one that doesn't support 4.1.

**Comment by zyzydo** [comment]
> @zyzydo, looks like it is failing when trying to import the character model using the addon BetterFBX.
> 
> It may be that you're using an older version of BetterFBX or one that doesn't support 4.1.

I'm using version 2.8-4.5.3

**Comment by michael-gh1** [comment]
@zyzydo Oh that'd do it. Latest one I've been using is 5.4.8

I believe there were breaking changes when going from Blender 3.x to 4.x

**Comment by zyzydo** [comment]
@michael-gh1 I tried both 3.6 and 4.1 blender, it won't let me Run Entire Script or Set Up Character for the models. Says the same error..

**Comment by michael-gh1** [comment]
Did you try a newer version of BetterFBX?

Try importing the character model using the BetterFBX addon directly if you want to test it.

**Comment by zyzydo** [comment]
@michael-gh1 I used the same version BetterFBX earlier and the model comes fine when I import directly from "Edit". Just doesn't work when I try it with the Setup Wizard.

**Comment by michael-gh1** [comment]
```py
            bpy.ops.better_import.fbx(
                'EXEC_DEFAULT',
                filepath=character_model_file_path,
            )
```
https://github.com/michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders/blob/main/setup_wizard/genshin_import_character_model.py#L115-L118


This is how I call BetterFBX — perhaps the method of calling it changed between the major versions 4 and 5. 

Either way, I think it is best to be on a newer version as it was breaking on older versions at some point when we upgraded from Blender 3.x to Blender 4.x

**Comment by zyzydo** [comment]
@michael-gh1 
![image](https://github.com/user-attachments/assets/fa4f7e7e-a0db-4ac7-a737-bc0f056d073e)
Oh, so whats the best version to be on? I also have mmd plug-in's in there if that affects it too.

**Comment by zyzydo** [comment]
@michael-gh1 Alright, I tried using version 5.4.8 better fbx. It shows this error. 
![image](https://github.com/user-attachments/assets/6d71cbad-0d17-479e-b003-f28f7033cedf)

**Comment by zyzydo** [comment]
@michael-gh1 It works now in 3.6 blender! I can import the characters, but when I do it in Goo Engine 4.0 it shows the error. 
![image](https://github.com/user-attachments/assets/39b50858-6845-40c0-8016-65ddd0fcd36c)

**Comment by michael-gh1** [comment]
For some reason your BetterFBX is trying to read some file in the BetterFBX addon, but it says the file is not found

![image](https://github.com/user-attachments/assets/bab38ecc-c8b6-4ac7-ba2a-3634b2144f90)

I don't know what the contents of those files should be, if it's something temporary generated at runtime or what.
