### ISSUE TITLE
Error while enabling the addon in blender 3.6.14

### ISSUE THREAD

**Issue by ArSrNa** [michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders#125]
I downloaded the add-on from the release v2.6.1, normally import to blender but it cannot enable directly.
![image](https://github.com/user-attachments/assets/1a07bd21-915e-47fa-941a-d316442b1147)

Errors are below:
````
Traceback (most recent call last):
  File "A:\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\86138\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\setup_wizard\__init__.py", line 20, in <module>
    from setup_wizard.genshin_import_materials import GI_OT_SetUpMaterials, HSR_OT_SetUpMaterials
ImportError: cannot import name 'HSR_OT_SetUpMaterials' from 'setup_wizard.genshin_import_materials' (C:\Users\86138\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\setup_wizard\genshin_import_materials.py)
````

The blender version is `3.6.14`

**Comment by ArSrNa** [comment]
The blender4.2 load and enable it normally
![image](https://github.com/user-attachments/assets/a55ece5c-aa34-4345-84d8-08600b17b8a9)
![image](https://github.com/user-attachments/assets/0e718a3c-2de1-4e4c-8558-c2aecccc8a2b)

**Comment by michael-gh1** [comment]
Hmm, for Blender 3.6, did you uninstall and then close Blender? And then re-open and try installing the addon?
Or just try to install the new version?

I think that error happens if you just try to overwrite the old version with the new version
